import { StartUpType, UserDataType } from "../../types/userPymeTypes";

export const SampleUser: UserDataType = {
  id: "30a97c3f-81ec-41bd-822e-a43eb63f60d6",
  firstName: "Maria Paula",
  lastName: "Medina",
  cityOfResidence: "Bogota",
  countryOfResicence: "Colombia",
  address: "Cll 28b # 13 -15",
  photoUrl: "./assets/images/profile.png",
  phone: "123456789",
  emailAddress: "mpaula456@hotmail.com",
  rights: "USER",
  pymeId: "daf2b76e-7a47-4c40-9ca6-bab74676aedf",
  pyme: {
    pymeId: "daf2b76e-7a47-4c40-9ca6-bab74676aedf",
    active: true,
    name: "Cube Ventures S.A.S",
    city: "Bogota",
    country: "Colombia",
    address: "Cll 26 # 68 - 35",
    emailAddress: "company@example.com",
    photoUrl: "some url",
    phone: "123456789",
  },
};

export const DefaultUser: UserDataType = {
  id: "30a97c3f-81ec-41bd-822e-a43eb63f60d6",
  firstName: "",
  lastName: "",
  cityOfResidence: "",
  countryOfResicence: "",
  address: "",
  photoUrl: "./assets/images/profile.png",
  phone: "",
  emailAddress: "",
  rights: "",
  pymeId: "",
  pyme: {
    pymeId: "",
    active: true,
    name: "",
    city: "",
    country: "",
    address: "",
    emailAddress: "",
    photoUrl: "",
    phone: "",
  },
};

export const SamplePymes: StartUpType[] = [
  {
    pymeId: "3453465465-N",
    active: true,
    name: "Cube Ventures S.A.S",
    city: "Bogota",
    country: "Colombia",
    address: "Cll 26 # 68 - 35",
    emailAddress: "company@example.com",
    photoUrl: "some url",
    phone: "123456789",
  },
  {
    pymeId: "5657545",
    active: true,
    name: "Circle Ventures S.A.S",
    city: "Bogota",
    country: "Colombia",
    address: "Cll 26 # 68 - 35",
    emailAddress: "company@example.com",
    photoUrl: "some url",
    phone: "123456789",
  },
  {
    pymeId: "4353565465",
    active: true,
    name: "Trinagle Ventures S.A.S",
    city: "Bogota",
    country: "Colombia",
    address: "Cll 26 # 68 - 35",
    emailAddress: "company@example.com",
    photoUrl: "some url",
    phone: "123456789",
  },
];
